# بسم الله الرحمن الرحيم
name: flutter_berichtsheft_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.0.1
  google_fonts: ^0.3.2
  outline_material_icons: ^0.1.1
  path_provider: ^1.5.1
  flutter_datetime_picker: ^1.3.4
  intl: ^0.16.1
  http: ^0.12.0+4
  sqflite: ^1.2.0
  path: ^1.6.4
  loading: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/avatars/avatar_dark.png
    - assets/avatars/avatar_hell.png
    - assets/images/LightLogoWithText.png
    - assets/images/DarkLogoWithoutText.png
    - assets/images/DarkLogoWithText.png
    - assets/images/LightLogoWithoutText.png