# بسم الله الرحمن الرحيم
name: flutter_berichtsheft_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.0.1
  path_provider: ^1.6.5
  google_fonts: ^0.3.2
  outline_material_icons: ^0.1.1
  flutter_datetime_picker: ^1.3.4
  intl: ^0.16.1
  http: ^0.12.0+4
  sqflite: ^1.2.0
  path: ^1.6.4
  loading: ^1.0.2
  dio: ^3.0.8
  jose: ^0.1.2
  pdf: ^1.5.0
  printing: ^3.1.0
  js: ^0.6.1+1
  crypted_preferences: ^0.0.2
  unicode: ^0.2.2
  shared_preferences: ^0.5.6+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/LightLogoWithText.png
    - assets/images/DarkLogoWithoutText.png
    - assets/images/DarkLogoWithText.png
    - assets/images/LightLogoWithoutText.png
    - assets/images/profile_light.png
    - assets/images/profile_dark.png
    - assets/images/null_delet_dark.png
    - assets/images/null_delet_light.png
    - assets/images/null_reports_dark.png
    - assets/images/null_reports_light.png
    - assets/images/null_search_dark.png
    - assets/images/null_search_light.png
    - assets/fonts/OpenSans-Regular.ttf
    - assets/fonts/arial.ttf