# بسم الله الرحمن الرحيم
name: flutter_berichtsheft_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^4.3.3
  path_provider: ^1.6.27
  google_fonts: ^1.1.1
  outline_material_icons: ^0.1.1
  flutter_datetime_picker: ^1.5.0
  intl: ^0.16.1
  http: ^0.12.0+4
  sqflite: ^1.3.2+2
  path: ^1.6.4
  loading: ^1.0.2
  dio: ^3.0.8
  jose: ^0.2.1+1
  pdf: ^1.13.0
  printing: ^3.7.2
  js: ^0.6.1+1
  crypted_preferences: ^0.0.2
  unicode: ^0.2.2
  shared_preferences: ^0.5.12+4
  build_runner: ^1.10.13
  build_web_compilers: ^2.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/LightLogoWithText.png
    - assets/images/DarkLogoWithoutText.png
    - assets/images/DarkLogoWithText.png
    - assets/images/LightLogoWithoutText.png
    - assets/images/profile_light.png
    - assets/images/profile_dark.png
    - assets/images/null_delet_dark.png
    - assets/images/null_delet_light.png
    - assets/images/null_reports_dark.png
    - assets/images/null_reports_light.png
    - assets/images/null_search_dark.png
    - assets/images/null_search_light.png
    - assets/fonts/OpenSans-Regular.ttf
    - assets/fonts/arial.ttf